### ISSUE TITLE
Error executing network-interface-checks: error opening metric file /var/cache/sensu/sensu-agent/network-interface-checks

### ISSUE THREAD

**Issue by daswars** [sensu/network-interface-checks#7]
We very often have the following error message:

The sensu agent must then be stopped, the cache folder emptied and then restarted.
This only happens with this asset.
Furthermore, the asset is packed incorrectly, so that it is not in the hash root folder but directly in /var/cache/sensu/sensu-agent/

```
Error executing network-interface-checks: error opening metric file /var/cache/sensu/sensu-agent/network-interface-checks
```

agent version
v6.10.0

Server
Sensu version 6.10.0

```
---
api_version: core/v2
metadata:
  created_by: sensu-flow
  labels:
    sensu.io/managed_by: sensuctl
    sensu.io/workflow: sensu-flow
  name: network-interface-health
  namespace: gsdd
spec:
  check_hooks: null
  command: >-
    network-interface-checks --state-file {{
    .annotations.network_interface_monitoring_state_file | default
    "/var/cache/sensu/sensu-agent/network-interface-checks" }}
    --exclude-interfaces {{ .annotations.excluded_network_interfaces | default
    "\"\"" }}
  env_vars: null
  handlers: []
  high_flap_threshold: 0
  interval: 30
  low_flap_threshold: 0
  output_metric_format: prometheus_text
  output_metric_handlers: null
  output_metric_tags:
    - name: entity
      value: '{{ .name }}'
    - name: host.name
      value: '{{ .name }}'
    - name: namespace
      value: '{{ .namespace }}'
    - name: os
      value: '{{ .system.os }}'
  output_metric_thresholds:
    - name: drop_in_rate
      null_status: 0
      tags:
        - name: interface
          value: '{{ .annotations.default_network_interface | default "eth0" }}'
      thresholds:
        - max: '0.0'
          min: ''
          status: 1
    - name: drop_out_rate
      null_status: 0
      tags:
        - name: interface
          value: '{{ .annotations.default_network_interface | default "eth0" }}'
      thresholds:
        - max: '0.0'
          min: ''
          status: 1
    - name: err_in_rate
      null_status: 0
      tags:
        - name: interface
          value: '{{ .annotations.default_network_interface | default "eth0" }}'
      thresholds:
        - max: '0.0'
          min: ''
          status: 1
    - name: err_out_rate
      null_status: 0
      tags:
        - name: interface
          value: '{{ .annotations.default_network_interface | default "eth0" }}'
      thresholds:
        - max: '0.0'
          min: ''
          status: 1
  pipelines: []
  proxy_entity_name: ''
  publish: true
  round_robin: false
  runtime_assets:
    - sensu/network-interface-checks:0.2.0
  secrets: null
  stdin: false
  subdue: null
  subscriptions:
    - linux
    - linux/network
  timeout: 10
  ttl: 0
  max_output_size: 0
  discard_output: false
type: CheckConfig

```
